// <auto-generated />
using Library.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library.Repository.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20241021075215_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Library.Models.Entity.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Isbn")
                        .IsUnique();

                    b.ToTable("T_Book", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Vincent V. Severski",
                            Isbn = "9788375542967",
                            State = 0,
                            Title = "Nielegalni"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Vincent V. Severski",
                            Isbn = "9788380156227",
                            State = 0,
                            Title = "Niepokorni"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Vincent V. Severski",
                            Isbn = "9788375546460",
                            State = 0,
                            Title = "Niewierni"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Vincent V. Severski",
                            Isbn = "9788375549836",
                            State = 0,
                            Title = "Nieśmiertelni"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Piotr Wroński",
                            Isbn = "9788381439961",
                            State = 1,
                            Title = "Plac Senacki 6PM"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Piotr Wroński",
                            Isbn = "9788382526370",
                            State = 1,
                            Title = "Dystopia"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Vincent V. Severski",
                            Isbn = "9788380159990",
                            State = 1,
                            Title = "Zamęt"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Vincent V. Severski",
                            Isbn = "9788381430043",
                            State = 0,
                            Title = "Odwet"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Vincent V. Severski",
                            Isbn = "9788381433839",
                            State = 0,
                            Title = "Nabór"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Piotr Wroński",
                            Isbn = "9788395755286",
                            State = 1,
                            Title = "Holub"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Piotr Wroński",
                            Isbn = "9788379653089",
                            State = 0,
                            Title = "Reset"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Piotr Wroński",
                            Isbn = "9788366498013",
                            State = 0,
                            Title = "Spisek założycielski. Historia jednego morderstwa"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Ian Flemming",
                            Isbn = "9780713481822",
                            State = 0,
                            Title = "Casino Royale"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Ian Flemming",
                            Isbn = "9780713481823",
                            State = 0,
                            Title = "Live and Let Die"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Ian Flemming",
                            Isbn = "9780713481824",
                            State = 0,
                            Title = "Dr. No"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Ian Flemming",
                            Isbn = "9780713481825",
                            State = 3,
                            Title = "From Russia, with Love"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Ian Flemming",
                            Isbn = "9780713481826",
                            State = 3,
                            Title = "Goldfinger"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Ian Flemming",
                            Isbn = "9780713481827",
                            State = 0,
                            Title = "The Spy Who Leved Me"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Ian Flemming",
                            Isbn = "9780713481828",
                            State = 0,
                            Title = "On Her Majesty's Secret Service"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Ian Flemming",
                            Isbn = "9780713481829",
                            State = 0,
                            Title = "You Only Live Twice"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
